default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_ENV_POSTGRES_DATABASE'] || Figaro.env.db_name %>
  username: <%= ENV['POSTGRES_ENV_POSTGRES_USER'] || Figaro.env.db_username %>
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] || Figaro.env.db_password %>
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || Figaro.env.db_host %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || Figaro.env.db_port %>
  pool: <%= Figaro.env.db_pool || 10 %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
