default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: products_catalog_dev

test:
  <<: *default
  database: products_catalog_test

production:
  <<: *default
  database: products_catalog_prod
